# Generated by Django 3.2.6 on 2021-08-21 04:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_users_tickerarray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='tickerarray',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
