# Generated by Django 3.2.6 on 2021-08-28 02:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_user_tickerarray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tickerarray',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
